module-name: test-infra
kind: kyma
bdba:
    - europe-docker.pkg.dev/kyma-project/prod/cors-proxy:v20250826-fc8ee8ad
    - europe-docker.pkg.dev/kyma-project/prod/dashboard-token-proxy:v20250826-fc8ee8ad
    - europe-docker.pkg.dev/kyma-project/prod/github-webhook-gateway:v20250826-fc8ee8ad
    - europe-docker.pkg.dev/kyma-project/prod/test-infra/rotate-service-account:v20250826-fc8ee8ad
    - europe-docker.pkg.dev/kyma-project/prod/test-infra/service-account-keys-cleaner:v20250826-fc8ee8ad
    - europe-docker.pkg.dev/kyma-project/prod/test-infra/signify-secret-rotator:v20250826-fc8ee8ad
    - europe-docker.pkg.dev/kyma-project/prod/test-infra/slackmessagesender:v20250813-f5280643
mend:
    language: golang-mod
    exclude:
        - '**/*_test.go'
checkmarx-one:
    preset: go-default
    exclude:
        - '**/*_test.go'
