name: 'Install dependencies'
description: 'Install Node.js 20 and @actions/core'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
      with:
        node-version: 22
    - run: |
        cd .github/actions/expose-jwt-action
        npm init -y
        npm install @actions/core
      shell: bash