# DEPRECATED: This file is no longer used in the Kyma project.
# It is kept for documentation purposes only.
# It was used to define automated approver rules for pull requests when automated approver was running on Prow.

apiVersion: v1
kind: ConfigMap
metadata:
  name: automated-approver-rules
  namespace: default
data:
  rules: |
    conditions:
      kyma-project:
        test-infra:
          dependabot[bot]:
            - changedFiles:
                - '.*'
          kyma-bot:
            - changedFiles:
                - '^docs/index.md$'
                - '.*\.yaml$'
                - '.*\.yml$'
                - '.*\.tf$'
                - '.*\.tfvars$'
                - 'development/tools/jobs/tester/tester.go'