name: all-checks-passed
on:
  pull_request:
    types:
      [
        opened,
        synchronize,
        reopened,
        ready_for_review,
        edited,
        labeled,
      ]
  merge_group:
   

jobs:
  all-checks:
    runs-on: ubuntu-latest
    permissions:
      checks: read
      contents: read
    steps:
      - uses: wechuli/allcheckspassed@5b5009ffd707b7c6759574c984bb666034b441eb # v2.0.0
        with:
          delay: '3'
          retries: '30'
          polling_interval: '1'