name: renovate-auto-approve

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - review_requested
      - synchronize
jobs:
  renovate-auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      id-token: write
    if: github.actor == 'renovate[bot]' && startsWith(github.head_ref, 'renovate/')
    steps:
      - name: Configure Workload Identity Federation
        id: auth
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3
        with:
          project_id: ${{ vars.GCP_KYMA_PROJECT_PROJECT_ID }}
          workload_identity_provider: ${{ vars.GH_COM_KYMA_PROJECT_GCP_WORKLOAD_IDENTITY_FEDERATION_PROVIDER }}

      - name: Fetch Kyma Bot Token For Auto Approve
        id: access-secret
        uses: google-github-actions/get-secretmanager-secrets@bc9c54b29fdffb8a47776820a7d26e77b379d262 # v3
        with:
          secrets: |
            GITHUB_TOKEN:${{ vars.GCP_KYMA_PROJECT_PROJECT_ID }}/${{ vars.GH_COM_KYMA_BOT_AUTO_APPROVER_TOKEN_SECRET_NAME }}

      - name: Auto Approve PR
        uses: hmarr/auto-approve-action@f0939ea97e9205ef24d872e76833fa908a770363
        with:
          review-message: "Auto approval of PR generated by Renovate Bot"
          github-token: ${{ steps.access-secret.outputs.GITHUB_TOKEN }}

      - name: Add auto-approved Label to PR
        run: gh pr edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ steps.access-secret.outputs.GITHUB_TOKEN }}
          NUMBER: ${{ github.event.pull_request.number }}
          LABELS: auto-approved