name: Manage Stale Issues

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  stale:
    uses: kyma-project/test-infra/.github/workflows/reusable-stale.yml@main
